meta_product_name: "French-Coin"
meta_title: "French Coin - Moula entre particuliers"
meta_description: "La question est vite répondue"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards